# =================================================
# Kitty 快捷键
# =================================================

# 对齐 WezTerm 的 disable_default_key_bindings = true
clear_all_shortcuts yes

# 剪贴板
map cmd+c copy_to_clipboard
map cmd+v paste_from_clipboard

# 工具
map cmd+u open_url_with_hints
map shift+enter send_text all \x1b\r
map cmd+alt+r reload_config_file
map cmd+, edit_config_file
map cmd+alt+, debug_config
map cmd+shift+, reload_config_file
map cmd+shift+p command_palette
map cmd+shift+r set_tab_title
map cmd+alt+period show_scrollback

# OS 窗口
map cmd+n new_os_window
map cmd+f toggle_fullscreen

# Tab
map cmd+t new_tab
map cmd+shift+t new_tab
map cmd+shift+w close_tab
map cmd+shift+/ select_tab
map cmd+shift+space last_used_layout
map cmd+[ previous_tab
map cmd+] next_tab
map cmd+shift+[ move_tab_backward
map cmd+shift+] move_tab_forward
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9

# 分屏 / Pane
map cmd+d launch --cwd=current --location=vsplit
map cmd+shift+d launch --cwd=current --location=hsplit
map cmd+w close_window
map cmd+enter toggle_layout stack
map cmd+shift+h neighboring_window left
map cmd+shift+j neighboring_window down
map cmd+shift+k neighboring_window up
map cmd+shift+l neighboring_window right
map cmd+shift+o focus_visible_window
map cmd+alt+left resize_window narrower
map cmd+alt+right resize_window wider
map cmd+alt+up resize_window taller
map cmd+alt+down resize_window shorter
map cmd+alt+0 resize_window reset

# 字体缩放
map cmd+= change_font_size all +1.0
map cmd+- change_font_size all -1.0
map cmd+0 change_font_size all 0
